apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    name: nginx
    environment: dev
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP


