apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    env:
     - name:  hello
       value: "hello"
     - name: there
       value: "there"