apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    name: config-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
    - name: COURSE
      configMapKeyRef:
       name: course-config
       key: COURSE
    - name: TRAINER
      configMapKeyRef:
        name: course-config
        key: TRAINER
